---
- hosts: localhost

############### Ensure to Maintain Alphabetical Order
  roles:
  - { role: alias, tags: ['alias'] }
  - { role: alltube, tags: ['alltube'] }
  - { role: folders, tags: ['folders'] } 
  - { role: netdata, tags: ['netdata'] }
  - { role: portainer, tags: ['portainer'] } 
  - { role: preinstall, tags: ['preinstall'] } 
  - { role: watchtower, tags: ['watchtower'] }